version: "3"

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: "citusdata/citus:10.2.3"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    env_file:
      - postgres.env
    networks:
      - liquibase-network
  worker:
    image: "citusdata/citus:10.2.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    env_file:
      - postgres.env
    command: "/wait-for-manager.sh"
    volumes:
      - citus-healthcheck-volume-liquibase:/healthcheck
    deploy:
      replicas: 2
    networks:
      - liquibase-network
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - citus-healthcheck-volume-liquibase:/healthcheck
    depends_on: 
      - master
    env_file:
      - postgres.env
    networks:
      - liquibase-network
  pgadmin:
    image: dpage/pgadmin4:6.3
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5555:80"
    volumes:
      - citus-pgadmin-data-liquibase:/var/lib/pgadmin
    networks:
      - liquibase-network

networks:
  liquibase-network:

volumes:
  citus-healthcheck-volume-liquibase:
  citus-pgadmin-data-liquibase:
